apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: alloy
      version: "0.6.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    controller:
      type: daemonset
    alloy:
      configMap:
        create: true
        content: |
          discovery.kubernetes "pods" {
            role = "pod"
          }
          discovery.kubernetes "nodes" {
            role = "node"
          }
          discovery.kubernetes "services" {
            role = "service"
          }
          discovery.kubernetes "endpoints" {
            role = "endpoints"
          }
          discovery.kubernetes "endpointslices" {
            role = "endpointslice"
          }
          discovery.kubernetes "ingresses" {
            role = "ingress"
          }

          prometheus.scrape "pod_metrics" {
            targets    = discovery.kubernetes.pods.targets
            forward_to = [prometheus.remote_write.grafana_cloud.receiver]
          }

          prometheus.remote_write "grafana_cloud" {
            endpoint {
              url = "https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push"
              basic_auth {
                username = env("USERNAME")
                password = env("TOKEN")
              }
            }
          }
    extraEnv:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: grafana-cloud-credentials
            key: username
      - name: TOKEN
        valueFrom:
          secretKeyRef:
            name: grafana-cloud-credentials
            key: token
